### PR TITLE
board, reply, inquiry, inquiryAnswer

### PR DESCRIPTION
**Pull request by ByungMMin**

### CODE REVIEW

**Review by seohansol — APPROVED** [review]
굿굿

**Review by KimChopl — APPROVED** [review]
굿굿굿굿

**Review by KimChopl — APPROVED** [review]
ㅁㄴㅇㄴㅁㅇㄴㅁㅇㄴㅁㅇㅁㄴ

**Review by SangEun24 — APPROVED** [review]
잘 됐으면 좋겠네여

**Pull request merged**
